[package]
authors = ["David LeGare <excaliburhissheath@gmail.com>"]
name = "rocket_derive"
version = "0.3.0"

[lib]
proc-macro = true

[features]
default = ["json"]
json = []
msgpack = []

[dependencies]
quote = "0.3.15"
syn = "0.11.11"
